name: Gatling Load Test

on:
  workflow_dispatch:

jobs:
  loadtest:
    runs-on: ubuntu-latest
    container:
      image: sbtscala/scala-sbt:eclipse-temurin-jammy-17.0.5_8_1.9.0_2.12.18
      options: --user root

    steps:
      - uses: actions/checkout@v4

      - name: Run Gatling Tests
        run: |
          sbt gatling:test
          ls -R -la target/

      - name: Upload Gatling Reports
        uses: actions/upload-artifact@v4
        with:
          name: gatling-results
          path: target/gatling
